### ISSUE TITLE
Start a Shuttle ESB in windows Service

### ISSUE THREAD

**Issue by moonspring** [Shuttle/shuttle-esb#41]
Hi,Eben,

I've solve that problem that I asked you last time.It is about starting two service bus in one process.Now I've already changed it to one service bus,it's ok now.

today,I also need to develop a windows service.When the computer is open,the service will start up,too.

And the windows service will contain a Shuttle service bus and some handlers.And the windows service can't start up because of the Shuttle ESB Service bus.

Why did this happen?

Regards,
MoonSpring

**Comment by dmelendez35** [comment]
Hi, MoonSpring
this you solved the issue? I'm having similar problem

**Comment by eben-roux** [comment]
Can you elaborate on your exact issue?

Typically you'd have only one service bus per process.  You *could* have more than one but it would be a rather odd situation and you'd probably be better off splitting them.

**Comment by eben-roux** [comment]
OK, so is this when you install your endpoint as a service?

Can you perhaps paste your code here so that I can have a look?

**Comment by dmelendez35** [comment]
thank for your response. I'm going to try to install it  as you mention using the Shuttle.Core.Host.exe  and not using my own windows service, I'll let you know how it goes and thank again  :)

**Comment by eben-roux** [comment]
Windows Services *can* be tricky.  You have to ensure that you are running the process (usually command prompt) as administrator when you *do* install the service.  However, other permissions issues may be at play also.  The credentials the service runs under may not necessarily have access to all the required resource (disk for logging, msmq queues, network shares, etc.).

Just some things to keep in mind :)
