### ISSUE TITLE
Dead letter support in MSMQ

### ISSUE THREAD

**Issue by ltvan** [Shuttle/shuttle-esb#48]
There should be an option to turn on dead-letter per end point in MSMQ. Newbies are easier to get stuck with the permission issue:
http://stackoverflow.com/questions/8519606/msmq-send-to-remote-private-queue-does-nothing

The bus may work in dev environment but when going production, somehow the queue created without Anonymous Logon permission and the message delivery is just failed without any exception or even nothing left on the outgoing queue. Storing dead-letter by default will be a rescue to ensure that the message won't be lost entirely.

**Comment by eben-roux** [comment]
Do you think that this is something that one should be able to control via a parameter?

Perhaps something like `msmq://./my-queue?useDeadLetter={true|false}` where it is `true` by default.

**Comment by ltvan** [comment]
Yeah, that's perfect.

**Comment by eben-roux** [comment]
- https://github.com/Shuttle/shuttle-esb-msmq/releases/tag/v3.4.3
- https://github.com/Shuttle/shuttle-esb-msmq/commit/15440d48210055d79e8700b970f3e0ccd7671e3f

**Comment by ltvan** [comment]
That's great. Thanks.
