### ISSUE TITLE
shuttle esb  Abnormal connection 

### ISSUE THREAD

**Issue by zhangxishi** [Shuttle/shuttle-esb#52]
I use the shuttle esb process, found that the MSMQ will be connected to the exception, resulting in a backlog of messages, and ultimately lead to insufficient resources, resulting in errors, I would ask, 
1, how to disconnect the MSMQ automatically re connect? 

2, if the expiration of the message how to clear?

**Comment by eben-roux** [comment]
I don't quite follow.  Where does the error occur?  Are you saying that the connection to msmq remains open and should be closed and reconnected?

When a message expires you simply do not handle it.  Any successful return from a message handler will acknowledge the message on the queue.  You can also use the following to expire a message:

```
bus.Send(new RegisterMemberCommand
{
	UserName = userName
}, c=> c.WillExpire(DateTime.Now.AddSeconds(5)));
```

**Comment by zhangxishi** [comment]
System MSMQ sometimes show the outgoing queue server has been waiting for the connection terminal, but the network is connected to the terminal, but the MSMQ is disconnected or has been waiting for the connection, will not be re established connection

**Comment by eben-roux** [comment]
I'm afraid I have no idea.  I am no genius when it comes to MSMQ.  Perhaps you should ask a question regarding the specific MSMQ issue on StackOverflow.  That may provide an answer quite a bit quicker.
