### ISSUE TITLE
Can JAVA subscribe Shuttle ESB event?

### ISSUE THREAD

**Issue by teryfly** [Shuttle/shuttle-esb#56]
If third part JAVA app what subscribe Shuttle ESB event , how to? thanks!

**Comment by eben-roux** [comment]
Hi,

Somehow I missed this issue...

A service bus is never intended to be exposed so if you need to notify a 3rd party java app I would suggest you subscribe using a normal .net endpoint and then push from there over some bridge, perhaps a rest call.

Hope that helps.

Eben
