### ISSUE TITLE
Store messages in JSON format

### ISSUE THREAD

**Issue by msvitlica** [Shuttle/shuttle-esb#58]
Hi,
I was wondering if there is a way to override message serialization to store messages in JSON ?

**Comment by eben-roux** [comment]
Hello,

You will need an implementation of the `ISerializer` interface:

https://github.com/Shuttle/Shuttle.Core.Infrastructure/tree/master/Shuttle.Core.Infrastructure/Serialization

I don't have a Json.Net implementation out-of-the-box but fortunately it is also rather simple to do :)

The just pass it into the configuration:

```
_bus = ServiceBus.Create(c => c.MessageSerializer(new JsonSerializer())).Start();
```

Perhaps something along the lines of (untested):

```
using System;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using Shuttle.Core.Infrastructure;

namespace Shuttle.Core.Json
{
    public class JsonSerializer : ISerializer
    {
        public Stream Serialize(object instance)
        {
            return new MemoryStream(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(instance)));
            
        }

        public object Deserialize(Type type, Stream stream)
        {
            return JsonConvert.DeserializeObject(new StreamReader(stream).ReadToEnd());
        }
    }
}
```

You just need to reference `Shuttle.Core.Infrastructure` and `Newtonsoft.Json`.  You'll probably want to tweak this a bit :)

Regards,
Eben

**Comment by msvitlica** [comment]
Seems like not too many lines of code is needed for this. I will try it out definitely.
Thank you very much,
Milan

**Comment by eben-roux** [comment]
I know json is quite popular but I tried to stay away from any 3rd party packages for the core.  So I stuck with the default .net xml serializer.

The idea was to make Shuttle as extensible as possible without too much effort.  Always room for improvement :)

It may be time to actually create a nuget package for a json serializer though.
