### ISSUE TITLE
Error when publish event version 10.0.6

### ISSUE THREAD

**Issue by carmonaca** [Shuttle/shuttle-esb#61]
Publish subscribe server

Exception description: 
System.NotImplementedException: NullSubscriptionManager     
at Shuttle.Esb.NullSubscriptionManager.GetSubscribedUris(Object message)     
at Shuttle.Esb.MessageSender.Publish(Object message, Action`1 configure)     
at Shuttle.Esb.MessageSender.Publish(Object message)     
at Shuttle.Esb.HandlerContext`1.Publish(Object message)  

I saw the code and I found the following things: 
    registry.AttemptRegister<ISubscriptionManager, NullSubscriptionManager>();

Method GetSubscribedUris:
 public IEnumerable<string> GetSubscribedUris(object message)
        {
            throw new NotImplementedException("NullSubscriptionManager");
        }
Could you please confirm if version 10.0.6 is implemented correctly? 

Thanks

**Comment by carmonaca** [comment]
Sorry, I fixed the problem. My bad I didn't install the dependency Shuttle.Esb.Sql.Subscription 10.0.0 with connection string name Subscription. After that the publish works correctly. 
Thanks

**Comment by eben-roux** [comment]
Apologies for not replying earlier (we're GMT+2).

Glad you got that sorted though...
