### ISSUE TITLE
Shuttle.ESB as Windows service

### ISSUE THREAD

**Issue by jirihora** [Shuttle/shuttle-esb#62]
Hello,

following Request / Response tutorial I have made the same example - it works fine. But when I replace Server Console application with Windows Service it does not work.

Widows service is identical copy of Server Console application with all NuGets, classes, references etc. I placed calling ServiceHost.Run<Host>() into OnStart() method. There is no error and service will not create message queues.

I read old topic about Window servicies - https://github.com/Shuttle/shuttle-esb/issues/41. Mentioned link to use Shuttle.Core.Host.exe is not working now.

I have installed service (with installutil.exe) as Administrator using Developer command prompt.

I have tried run service as Local System user also as my account - nothing helped.

What I am trying for is to have listener waiting for messages (Windows service) and a client connected to server where will be this Windows service. When Windows service get message, it will call another service (WCF) with parameters from message (nice to have: and send response to client).

Could you help me with that?

**Comment by eben-roux** [comment]
Hi,

Apologies for not getting back to you earlier.

If you need to install the console application as a service you should use the actual console application with the `/install` parameter, e.g.: `Shuttle.RequestResponse.Server.exe /install`

Did that bit not work?

A client would typically not interact directly with a service bus.  I guess it would also depend on what you mean by "client" though :)

Perhaps you can give me some more information on what you are trying to achieve and I'll help where I can.

**Comment by jirihora** [comment]
Hello,
thank you so much for the answer!

Installing client Console application with /install command worked for me.

---

My "client" is now another Windows service on the same station, which has timer and in Timer.Elapsed is my logic:

- write to file - timer ticked 
- send message to server (RegisteredMemberCommand object with property Guid MessageId) 
- write to file - message has been sent 
- in case of exception - write to file exception.Message

Server has in ProcessMessage method following logic:  
- write to file - message has been recieved 
- send client response (MemberRegisteredEvent object with property string Response and Guid ResponseId)

---

My problem is that server is responding for previous message (see following log).

Client: timer tick at 09.08.2018 9:39:47.
Client: message cedf1dae-dab2-439d-bea6-19166c5f7fee sent at 09.08.2018 9:39:48.
Server: Message cedf1dae-dab2-439d-bea6-19166c5f7fee recieved.

Client: timer tick at 09.08.2018 9:39:58.
Client: message 7c61e3e4-20be-4dbe-b4fc-0166a14a9841 sent at 09.08.2018 9:39:58.
Client: Response from server for messageId cedf1dae-dab2-439d-bea6-19166c5f7fee recieved at 09.08.2018 9:39:58 - responseId: e2d95f2c-72aa-48e0-a692-f0b19b531700
Server: Message 7c61e3e4-20be-4dbe-b4fc-0166a14a9841 recieved.

Client: timer tick at 09.08.2018 9:40:08.
Client: message 806ec4e0-a77b-4405-af28-47cba984e7dc sent at 09.08.2018 9:40:08.
Client: Response from server for messageId 7c61e3e4-20be-4dbe-b4fc-0166a14a9841 recieved at 09.08.2018 9:40:08 - responseId: bd48db3f-d54c-44a2-8b7c-6d86ece370cd
Server: Message 806ec4e0-a77b-4405-af28-47cba984e7dc recieved.

Client: timer tick at 09.08.2018 9:40:18.
Client: message 7c1545b2-c51b-475b-9da9-71cb74f1b181 sent at 09.08.2018 9:40:18.
Client: Response from server for messageId 806ec4e0-a77b-4405-af28-47cba984e7dc recieved at 09.08.2018 9:40:18 - responseId: 9bbc8d09-8086-40f6-ae64-606eb98e78ba

---

I am trying to achiev following:
1. Client (Window service) do something in an interval
2. Client send message to server
3. Server call WebService method with parameters from message
4. Server wait for WebService response
5. Server send result to client as response
6. Client do something based on response

Maybe this is not correct use of ESB (as you mentioned "client would typically not interact directly with a service bus") but I must to use ESB for some reason.

---

I have tried to clear message queues - not helped.

Do you have any idea how to fix this issue?

**Comment by eben-roux** [comment]
I'm just popping out so I'll give a more detailed response a bit later.

In the meantime I don't see anything wrong in your log.  Keep in mind that the communication is not synchronous.  The "client" sends a message and *may* have a handler for a response.  That is one-way communication.

The "server" processes a message and *may* send a response or even publish an event depending on what you aim to achieve.  In your case a reply is sent (also only possible if the sender has an inbox, which you do seem to have).  This is *also* one-way communication.

I'll elaborate on your architecture a bit later.

**Comment by eben-roux** [comment]
I got home later than anticipated yesterday so apologies for the late response.

Hopefully my previous comment made sense.  Your use-case seems fine though.  Keep in mind that the communication with the web-service may fail at various points so you may need to consider some idempotent behaviour.

As an example we may have a transaction that needs to be posted over a web-service.  We can assign a unique id (such as the guid used as the `MessageId`).  We can now perform the idempotence check in two ways.  First we can ask the web-service whether a given transaction id has been processed and, if not, we send our request.  We do this since the web-service *may* process the request but the response fails to reach us.

Another option may be that the web-service handles the idempotence.  We send the request and the web-service internally checks whether or not the transaction has been processed and then either processes it when it hasn't yet been processed and *then* send back and OK *or* it simply sends back an OK for a transaction that has already been processed.

**Comment by jirihora** [comment]
Hi,

your reminder that communication is asynchronous was helpful. Now (I hope) I understand the principal of ESB. Due to this I changed implementation of registering container and starting bus and now it works as I expected.

Thank you very much for your help.
